apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: devops-agent
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      env:
        - name: JENKINS_SECRET
          valueFrom:
            secretKeyRef:
              name: jenkins-agent
              key: jenkins-secret
        - name: JENKINS_AGENT_WORKDIR
          value: /home/jenkins/agent
        - name: JENKINS_NAME
          value: k8s-agent
        - name: JENKINS_URL
          value: http://jenkins.jenkins.svc.cluster.local:8080
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
  volumes:
    - name: workspace-volume
      emptyDir: {}
  restartPolicy: Never
