apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: devops-agent
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:alpine
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']

    - name: docker
      image: docker:24.0.2-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock

    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - cat
      tty: true

  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
